// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQzBY_ZeOYCB3LvI_nOrCN5dqFgDz-ofY',
    appId: '1:427307525854:web:f82a776972555c6de2044f',
    messagingSenderId: '427307525854',
    projectId: 'crud-productos-flutter-app',
    authDomain: 'crud-productos-flutter-app.firebaseapp.com',
    storageBucket: 'crud-productos-flutter-app.firebasestorage.app',
    measurementId: 'G-X7K8ZKEK2H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjCHH5bwasaJBxgYh-JlzuYm7uJgxBJ-M',
    appId: '1:427307525854:android:da5c8e6d3629d510e2044f',
    messagingSenderId: '427307525854',
    projectId: 'crud-productos-flutter-app',
    storageBucket: 'crud-productos-flutter-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj8D03LIe5o_GBvDuQrmvdbSxYnBUmL-s',
    appId: '1:427307525854:ios:4f4acfa4c303684ae2044f',
    messagingSenderId: '427307525854',
    projectId: 'crud-productos-flutter-app',
    storageBucket: 'crud-productos-flutter-app.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );
}
